name: adventure_care
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    get: ^4.6.1
    sizer: ^2.0.15
    pin_code_fields: ^7.4.0
    flutter_animation_progress_bar: ^2.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/

    fonts:
        - family: Nunito
          fonts:
              - asset: assets/fonts/Nunito-Black.ttf
                weight: 900
              - asset: assets/fonts/Nunito-ExtraBold.ttf
                weight: 800
              - asset: assets/fonts/Nunito-SemiBold.ttf

    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
